[package]
name = "serenity-mre"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
serenity = { git = "https://github.com/mkrasnitski/serenity.git", branch = "label-component" }
serde_json = "1.0.145"
